compressionLevel: mixed

nodeLinker: node-modules

plugins:
  - checksum: 4bb33aafebc0e4ebb2481c3a3aa3de899776b94bc26b45430a47c325d8b72fdb9d58bbaa44250f4acb18d0b39b91aea4d9cbc247f072a93ebff9caa9fa74b59e
    path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: bundles/@yarnpkg/plugin-engines.js
